services:
  pebble:
    image: ghcr.io/letsencrypt/pebble:latest
    command: pebble -config /test/config/pebble-config.json -strict -dnsserver challtestsrv:8053
    # ports:
    #   - "14000:14000"  # HTTPS ACME API
    #   - "15000:15000"  # HTTPS Management API
    networks:
      - test
  pebble-eab:
    image: ghcr.io/letsencrypt/pebble:latest
    command: pebble -config /test/config/pebble-config-external-account-bindings.json -strict -dnsserver challtestsrv:8053
    volumes:
      - ./fixtures/pebble-eab/cert.pem:/test/certs/localhost/cert.pem:Z
      - ./fixtures/pebble-eab/key.pem:/test/certs/localhost/key.pem:Z
    networks:
      - test
  challtestsrv:
    image: ghcr.io/letsencrypt/pebble-challtestsrv:latest
    depends_on:
      - pebble
      - pebble-eab
    command: pebble-challtestsrv -http01 "" -tlsalpn01 "" -dns01 ":8053"
    ports:
      - "8055:8055"      # HTTP Management API
      - "8053:8053/tcp"  # DNS API
      - "8053:8053/udp"  # DNS API
    networks:
      - test
  vault:
    image: vault:1.6.2
    # ports:
    #   - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=supersecret
    networks:
      - test
  app:
    build: .
    depends_on:
      - pebble
      - pebble-eab
      - challtestsrv
      - vault
    env_file:
      - .env.dev
    networks:
      - test
  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    depends_on:
      - pebble
      - pebble-eab
      - challtestsrv
      - vault
    command: ["true"] # do not start the container when `docker-compose up` is executed
    networks:
      - test
networks:
  test:
    driver: bridge